### ISSUE TITLE
Feature: Allow nested setting files

### ISSUE THREAD

**Issue by javibravo** [MediaMath/lambda-cron#14]
Currently **LambdaCron** allows to set environment options in one file (*~/.lambda-cron.yml*). Could be good to be able to set environment options in different files (different projects).

Proposal:

1. Be able to include setting files in *~/.lambda-cron.yml*. For example:

```yaml
my-project-a:
    settings: /path/to/my-project-a/lambda-cron.yml
my-project-b:
    settings: /path/to/my-porject-b/lambda-cron.yml
```
